### ISSUE TITLE
LEARNING: release and test first version of unified Mozilla Leadership Network curriculum

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/Goals#1]
- Release and test first version of a unified Mozilla Leadership Network curriculum, resources and tools
- Streamline systems for content authoring (editing, publishing, localizing, remixing)

**Comment by ldecoursy** [comment]
@chadsansing or @hannahkane Can you provide a 1-2 sentence update here on our progress in Jan? Brief is best, a la the "story of Jan" email Mark shared. Using this repo just to track monthly progress towards top line H1 deliverables.

**Comment by hannahkane** [comment]
WRT database: January was about conducting a research project to investigate how educators currently access learning materials. Also began process of moving web lit curriculum to new template (can potentially be used for Leadership Network curriculum).

**Comment by ldecoursy** [comment]
Thanks @hannahkane

**Comment by ldecoursy** [comment]
## January
- MoCo/MoFo Curriculum team created smaller working groups to begin drafting curriculum guidelines, a manifesto, and possible frameworks for the leadership curriculum.
- Curriculum database - we conducted a research project to investigate how educators currently access learning materials.
- Curriculum templates - we started to move Web Lit Basics II curriculum to a new template, which may be used for upcoming Leadership Network curriculum.

**Comment by chadsansing** [comment]
The MoCo/MoFo Mozilla Curriculum team began scoping out small-group
projects in support of the leadership curriculum (e.g. drafting a set of
curriculum guidelines and a manifesto) and discussed possible frameworks
for the curriculum itself.

On Fri, Jan 29, 2016 at 5:47 PM, Lainie DeCoursy <notifications@github.com>
wrote:

> Thanks @hannahkane <https://github.com/hannahkane>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/Goals/issues/1#issuecomment-177006427>
> .
>



-- 
Chad Sansing
Curriculum Developer, Web Literacy
Mozilla Foundation
chad@mozillafoundation.org
@chadsansing

**Comment by ldecoursy** [comment]
@chadsansing Can you help provide a line or two about our progress in Feb?

**Comment by chadsansing** [comment]
## February
- Leadership curriculum aligned with MoCo Participation team's Leadership Framework.
- Initial scoping under review.
- Assigned to @zee-moz & @chadsansing.

**Comment by ldecoursy** [comment]
## March
- Determined scope and sequence of the Leadership Curriculum. Developed a template and started drafting modules.
- Launched Web Literacy Map 2.0
- Drafted holistic program design framework to define core values and characteristics across MLN.

**Comment by ldecoursy** [comment]
ping @kaythaney @chadsansing @zee-moz for top line progress in April. Thanks!

**Comment by ldecoursy** [comment]
ping @kaythaney @chadsansing @zee-moz - realize now we didn't get to April here either. Can you share a few top line bullets on progress for April/May?

**Comment by ldecoursy** [comment]
See #12 for H2 Learning goal - closing this now.
