### ISSUE TITLE
CONVENING: document a shared approach for convenings and local groups across Mozilla

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/Goals#2]
- Create a shared and well-documented approach for convenings and local groups across Mozilla
- Including updated playbooks and a shared convening calendar

**Comment by ldecoursy** [comment]
## January
- Worked to clarify the mandate of the new Convenings team. Hosted Hive Chicago Buzz, and began audit to document characteristics of Mozilla convenings, and how they help develop leadership.
- Drafted first version of MoFo Convenings calendar.

**Comment by edrushka** [comment]
We're very close to sharing the convenings plan (i.e. our mandate) - just working through one last item with Claw. 

As shared already, we've audited Hive Chicago Buzz and are documenting the takeaways. In addition, here's what else we've done:
- [design needs] (https://github.com/MozillaFoundation/plan/issues/683)
- [schedule app] (https://github.com/MozillaFoundation/plan/issues/710)
- [convenings calendar] (https://github.com/MozillaFoundation/plan/issues/708)

Next up:
- Google Drive for convenings assets (templates, documentation, design resources etc.)

**Comment by ldecoursy** [comment]
@edrushka Can you add a comment about the story of Feb similar to above?

**Comment by edrushka** [comment]
## February
- Scoped [improvements to Schedule app](https://github.com/MozillaFoundation/plan/issues/710) and identified [MVP changes](https://github.com/MozillaFoundation/plan/issues/747). 
- Wrote and workshopped Convenings Team 2016 Plan, including identifying what resources and training we need to provide for staff and community.
- Began creating [graphic asset templates](https://github.com/MozillaFoundation/convenings/issues?q=is%3Aissue+is%3Aopen+label%3ADesign) for any size/any budget events with Sabrina.
- Began planning MozRetreat, the collaborative workweek for shaping the festival with community, with Mark & Claw.
- Finalized dates and location for MozFest 2016.
- Wrote [staff guide for presenting on the Monday Project Call](https://docs.google.com/document/d/13HYsqi0B-MIXvr08FR87JOC4hgYT4ZtA31AF_6oqiUM/edit) with Kevin.
- Began examining how to measure impact of events with Adam and Matthew W.
- Identified extraordinary event attendees and began planning ["stepping stones"](https://github.com/MozillaFoundation/convenings/issues/4) to develop them as members of our network with Robert.
- Helped Lindsey and Michelle brainstorm the Gigabit x IOT convening.
- Clarified convenings and MozFest budgets with Angela.
- Kicked off MozFest design planning with Cassie.
- Started a :tulip: [beautiful new repo](https://github.com/MozillaFoundation/convenings/issues) :tulip: for our work.
- Began consolidating [all MoFo event documents in one place](https://github.com/MozillaFoundation/convenings/issues/7) and pitching this as a use-case for Calypso with Hannah.

cc @Saallen in case there's anything else I've forgotten.

**Comment by chrislarry33** [comment]
So much momentum!!! I love it. @edrushka if you could pick one of the above as part of a larger mofo story of feb, what would it be?

**Comment by Saallen** [comment]
Additional points @edrushka 
- Ravensbourne monthly planning meetings have started
- Began work on designing job description for additional convenings team member
- Attended WoW event in Berlin
- Intensional and continous planning and mapping the strategy 2020 goals across all our work

Personal team goals
- hit our team stride with meetings
- Celebrated mutual love for tea

**Comment by edrushka** [comment]
@chrislarry33 @Saallen I'd propose the "stepping stones" planning (how to get outstanding people into our network by using convenings as stepping stones) is the best one to highlight. 
- it's a tangible plan for building our network with strong emerging leaders
- it offers a real benefit to people at early stages in their career (career growth, leadership training, building a network of peers) 
- we're making a concerted effort to include girls and women on this list
- talking with @KalpanaSimhan indicates this could potentially be a great way to use some underspent grant $ - it will benefit us, benefit the community, and please funders.

**Comment by ldecoursy** [comment]
@Saallen @edrushka Ping for March highlights - if you can keep to 3-5 bullets that would be great!

**Comment by Saallen** [comment]
## March
- Large focus on Mozretreat 2016, inviting key contributors, desiging the logistical and program elements
- Kick off key focus areas for MozFest 2016 as hotel scoping, opening Website [repo](https://github.com/MozillaFoundation/2016.Mozillafestival.org) , New staff and community wrangler support and onboarding new partners such as the Tate Modern
- Worked w MSL on their Global Sprint, assisting with doc and tech requirements
- Started to design Convenings team All hands meet-ups

**Comment by ldecoursy** [comment]
ping @Saallen @edrushka for April top line progress bullets. Thanks!

**Comment by edrushka** [comment]
## April
- Large focus on Mozretreat 2016. Interviews with all participants. Designing agenda.
- Updated MozFest website
- Kicked off several MozFest areas including design, tech pieces
- Consulted on design and dev work for schedule app
- Planning June 1 'Call for Proposals' update to MozFest site
- Working with Michelle & Jon on IOT Dundee event design
- Working with Katie on Hive Chattanooga event design

**Comment by ldecoursy** [comment]
ping @edrushka @Saallen for May

**Comment by edrushka** [comment]
## May
- Hosted MozRetreat (planning session for MozFest 2016) in Berlin
- Worked with Space Wranglers to get all Space Narratives written
- Designed call for proposals (including translation into French, Spanish & Arabic)
- Developed mainstage and Discussion & Debate ideas with Kevin
- Updated MozFest website with 2016 information and Call for Proposals form
- Worked with Katie on Hive Chattanooga event design
- Short list MozFest Hotel and went on site visits
- Developed MozFest Travel policy for 2016
- Held first Space Wrangler call for 2016

**Comment by Saallen** [comment]
cc @edrushka added some more points above 🏨

**Comment by ldecoursy** [comment]
Closing this ticket. See #13 for H2 Convening goals.
