### ISSUE TITLE
MEMBERSHIP: test our value proposition for network members

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/Goals#3]
- Test our value proposition for network members. 
- Establish systems that guide effective membership, affiliation and drive innovation.

**Comment by ldecoursy** [comment]
## January
- Held first MLN Affiliate Policy working group meeting, where we identified commonalities/differences in how different programs identify/outreach to our key audiences, as well as the value/benefits those audiences see in participating with our work. Also defined new questions we need to explore in order to inform a policy.

**Comment by ldecoursy** [comment]
## February
- Network Strength KPI - Developed plan and draft survey questions. Reviewed these with internal teams and external network evaluation consultants. 
- Finalized plans for launching new Mozilla Learning member engagement channels in March (newsletter, community call, curriculum workshop)
- Affiliate Policy working group continued discovery phase, sharing learnings and challenges related to what we can/can't provide to potential affiliates. 
- Network Pulse – Developed [a framework](https://github.com/MozillaFoundation/plan/issues/746#issuecomment-189005224) for exploring ways to foster sharing among network members. Explored a [prototype](https://xmatthewx.github.io/network-pulse/) to facilitate this.

**Comment by ldecoursy** [comment]
## March
- Distributed Network Mapping surveys to inform membership proposition
- Completed discovery phase for Affiliate Policy working group
- Hired consultant to work on rewards and recognition programs to build sense of belonging

**Comment by ldecoursy** [comment]
@adamlofting ping for brief April/May update re: Network Mapping

**Comment by adamlofting** [comment]
## April/May
- The Network Mapping Surveys closed, and the [analysis is underway here](https://docs.google.com/document/d/17NQKl7QdlpxdAaDkm36Gtlxla6WHTu1Qn1OJ0xktMYo/edit#). 
- Developed roadmap for the next 12 months of this work. 
- Developed plan for recognizing affiliations (executives & champions) and contributions (young, emerging, professional leaders)

**Comment by ldecoursy** [comment]
Also: 
* Developed plan for recognizing affiliations (executives & champions) and contributions (young, emerging, professional leaders)

**Comment by ldecoursy** [comment]
Closing this ticket. See #15 for updated H2 Goals for Membership
