### ISSUE TITLE
INFRASTRUCTURE: support priority initiatives around Convening, Learning and Membership

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/Goals#4]
- Provide strong tech infrastructure for our priority initiatives, Convening and Learning. 
- Streamline and strengthen our CMS + CRM.

Related tickets from /plan: https://github.com/MozillaFoundation/plan/issues?q=is%3Aissue+is%3Aopen+label%3A%22MLN+Infrastructure%22

**Comment by ldecoursy** [comment]
## January

Began process to prioritize work to happen in remainder of Q1 and Q2

**Comment by ldecoursy** [comment]
## February
- Researched self-directed online training platforms for Clubs and other learning programs
- Localized Thimble
- Started implementing a CMS including the creation of a set of standard layouts that match real use cases
- Provided html and markdown templates, training, and support to staff authoring content in the meantime, as an interim solution
- Designed asset templates for convenings
- Set scope for next iteration of the Schedule app development, and framed a round of ideation to explore opportunities that might extend the in-person experience.

**Comment by xmatthewx** [comment]
Updated comment above.

**Comment by ldecoursy** [comment]
@hannahkane @xmatthewx Can you help with March highlights (sorry, thought I pinged about this earlier)

**Comment by hannahkane** [comment]
## March
- Released a prototype of a new web-based chat platform with the goal of offering a more inclusive, inviting and integrated experience than IRC
- Released interactive Web Literacy Map (v2.0)
- Finished build-out of CMS v1 including teach.m.o hooks (release is blocked on a hosting issue)
- Designed and built templates for use in CMS and beyond to unify web experiences and speed up production.
- Design and developed a bootstrap theme to align styles across web properties and speed up production.
- Began first test of new approach to building out web properties with the Science site refresh including:
  - new IA that adheres to Mofo-wide IA plan
  - wireframes and comps that represent modular, cross-org approach to design
  - "hybrid" engineering approach that makes use of CMS for self-service aspects of web content, as well as moving to Django framework for backend
- Distributed knowledge of Python, Django, Docker and other technologies across team

**Comment by hannahkane** [comment]
@xmatthewx and @simonwex - I started a list, but need you both to add to / fix what I've written. :)

**Comment by hannahkane** [comment]
@ldecoursy - does the Web Lit Map belong here, or does that go in a different ticket?

**Comment by xmatthewx** [comment]
You might add emphasis on templates. 
 * Designed and built templates for use in CMS and beyond to unify web experiences and speed up production. 
 * Design and developed a bootstrap theme to align styles across web properties and speed up production.  

While I'm here, April WIPs:
 * Built a lightweight Clubs event reporting tool to better track and measure global activity and impact. Began field tests with lead users. 
 * Revised Event App architecture to prepare for Mozfest and enable future prototypes. Developed feature concepts to capture and extend the event experience into the weeks that follow.

**Comment by simonwex** [comment]
:+1:  on adding Web Literacy Map. I also agree with the emphasis @xmatthewx is suggesting. 

I think adding [Mozilla Chat](https://chat.mozillafoundation.org/mozilla) would be a good and significant piece of work:


> A prototype of a new web-based chat platform with the goal of offering a more inclusive, inviting and integrated experience than IRC

**Comment by hannahkane** [comment]
in general, @ldecoursy, do you want these monthly updates to include completed work or also work-in-progress?

**Comment by ldecoursy** [comment]
Ideally it's a top-line summary (5-7 bullets) of progress in that month, so can be a little of both. If you can edit your comment above to incorporate @xmatthewx's comments I'll  delete some of the discussion-y comments so this thread just has one comment per month.

**Comment by ldecoursy** [comment]
ping @hannahkane for April highlights (how time flies!)

**Comment by hannahkane** [comment]
## April
- Conducted security and legal review of Teachable platform for Club Captain training
- Released beta version of Clubs Event Reporter tool
- Refactored event app for use by multiple events. Prepped a version for London All-Hands.
- Continued ideation on rich Event App features
- Further improvements to curriculum template design, in response to user feedback
- Continued progress on Science site refresh
- Released Badges implementation (using Cred.ly) on a staging server

**Comment by ldecoursy** [comment]
ping @hannahkane @xmatthewx for May

**Comment by hannahkane** [comment]
## May
- Released new Science site look and feel and backend at science.mozilla.org
- Put the CMS on a staging server and began to test it and resolve found issues
- Refined Club Captain application form based on feedback from program staff
- Supported prototype design and build for Digital Skills Observatory
- Conducted discovery and estimation process for potential partnership with Code.org around the Thimble Classroom features
- Made necessary updates to MozFest website
- Provided diagrams for Open Leadership Curriculum
- Resolved mixed content issue with X-Ray Goggles

**Comment by ldecoursy** [comment]
Closing this ticket. See #16, #17 and #18 for updated H2 Production goals
