### ISSUE TITLE
INNOVATION: develop research, collaboration tools and community tech talent

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/Goals#5]
- Drive research that aligns with our strategy and informs thought leadership publications like State of the Web
- Develop collaboration tools 
- Support community tech talent

**Comment by ldecoursy** [comment]
## January

Team is working to clarify and prioritize next steps.

**Comment by ldecoursy** [comment]
## February
- Network Strength KPI - Developed plan and draft survey questions. Reviewed these with internal teams and external network evaluation consultants. 
- MatterMoz
- Network Pulse – Developed [a framework](https://github.com/MozillaFoundation/plan/issues/746#issuecomment-189005224) for exploring ways to foster sharing among network members. Explored a [prototype](https://xmatthewx.github.io/network-pulse/) to facilitate this.

**Comment by ldecoursy** [comment]
@simonwex @adamlofting Any edits/additions to above? Reminder the goal here is brief update on monthly progress towards H1 goals...

**Comment by adamlofting** [comment]
I made a couple of edits. Thanks.

**Comment by ldecoursy** [comment]
@simonwex Can you add a quick note about MatterMoz if you agree it belongs here?

**Comment by ldecoursy** [comment]
Closing this ticket. Updated thinking recognizes that other MLN buckets of work create conditions for **innovation** - it's not a separate bucket of work.
