### ISSUE TITLE
AGENDA-SETTING: run a learning-focused encryption campaign

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Goals#6]
Plus: partnerships highlighting women in technology / International women’s day events.  
- [ ] 1) Launch campaign around privacy /  encryption
- [ ] 2) Launch campaign around International Women’s Day and “mini” Maker Party 
- [ ] 3) Develop MVP for State of Web prototype using encryption as model topic 
- [ ] 4) Identify & recruit organization allies 

Full context and plan: http://mzl.la/1ZNayE7

**Comment by OpenMatt** [comment]
### January Update
- **Encryption campaign.** We are making excellent progress on our privacy / encryption campaign, launching Feb 8. Details here: http://mzl.la/encryption
- **State of the Web.** Developed a draft slide deck that describes the goal and approach. Will have a more visible / shareable / wiki in Q2.

**Comment by OpenMatt** [comment]
@bhuvanshri is there a link to a document / wiki / thing in progress we can include in terms of an update for 3 above?

**Comment by benrito** [comment]
Confused about the bug description and relationship between 1 - 3—possible to unpack?

Regarding State of the Web, @bhuvanshri can share a slide deck that describes the goal and approach, but we're won't be in a outside shareable / wiki / production mode until Q2.

If you can unpack the PM goal here we can provide more suitable documentation.

Cheers!
Ben
